# download stock price data, write to hdf5 data file
import argparse
import subprocess
import numpy as np
import h5py

nyse_nasdaq = [
'HAL','CASS','GGB','RIGL','NOC','BBSI','JRO','PPS','GLDD','VNET','ARL','NPV','PHT','TISI','BIND','HES',
'BYM','TBNK','HCA','XL','VNTV','FMX','"','MMC','CHD','SRE','KW','CHKP','FLEX','DXPE','AMZN','CSC','STL',
'LXK','PRTY','SSL','BGH','AVID','BK-PC','ASG','CBA','HNT','CNOB','SHLD','JD','VTL','EFII','PFH','CVI',
'TNK','SGMO','UMPQ','C-PP','EGY','KURA','SSS','SERV','TTI','BG','TRU','ORC','XKE','LLTC','NCZ','DCA',
'BBEPP','RBS-PS','RLD','SWK','VAC','GLOB','PLAB','JACK','RBS-PF','RIO','NCI','REV','ECR','TX','CMN','ABR',
'SQNM','JAH','LFC','PKT','LVNTA','DTV','RRD','BLD-WI','KFRC','MXIM','JHY','MOH','LILAK','NTC','PACB',
'FFIN','TSS','LAD','WFC-WT','STR','BANC','NCIT','MHN','DPM','TAP-A','ZTS','THW','ROP','DCM','KMPR','AFGE',
'CUK','ENI','AMSF','LH','JSD','RBC','GMT','PEGA','EMMS','BXE','RMAX','USA','UAM','N','TDE','ELOS','DXLG',
'TNAV','DKS','SIVBO','AVOL','BME','PHM','GNTX','WBMD','ACRS','JW-A','AREX','PNI','EFX','BIP','DMTX','DXCM',
'MGNX','FBP','TAC','VHI','BXMT','QVCB','ARWR','GOOG','CHU','HAS','PGND','WTW','TCRZ','GMED','AVX','NYCB-PU',
'CFG','TANO','OTIC','EMCI','EXPR','INTU','NWE','APC','CBX','JRI','AEL','DPZ','KYN-PE','FAC','PPC','PSUN',
'ESE','PZE','QTS','IRC-PB','LMOS','AED','PCBK','JBLU','NSP','QDEL','ACBI','CIGI','MCK','PMBC','COF','FSTR',
'CBM','GURE','DDC','WBC','SAR','MYOK','AMPH','HMSY','TGH','GAINN','NPBC','POM','JASO','AFGH','ONCE','FET',
'AMBA','FNBC','DB','GCH','PRAH','QVCA','JCE','BFK','INZ','PFX','LHCG','ITRI','AAN','STWD','VISN','SCSC',
'SBUX','MTSN','OA','NLY-PA','RCS','DHI','ASC','PMX','X','MHFI','GKOS','EFF','LGCYP','EXD','HPF','GPX',
'AFC','FXEN','NXST','UAL','ATHM','SBS','FSIC','IBTX','SCLN','DSX','DEL','SCHN','RATE','KMI-WT','CRMT',
'HURN','MYE','TOL','CRL','PLT','MW','MPO','SDRL','NUVA','CPSI','ETX','BAMM','COLM','RLYP','DRII','TRIB',
'TSLA','DHT','ORCL','ECL','COST','MWG','IAE','ACI','BSE','LION','CNA','IPCM','WTFC','MYL','MYCC','HAYN',
'BLKB','NSH','ANTM','SRPT','MUSA','ATR','PNTA','FDEF','KWR','HTGY','UZC','MESO','AZZ','FNSR','SRCL','ZLTQ',
'ENB','RSO','RS','VVC','DSX-PB','ICA','KMT','HOLX','CPL','MOD','ECA','XCO','IMKTA','MITL','BOE','GEH',
'AVH','SSRI','GXP-PD','UHS','DERM','FRED','CCP','NEA','ABCO','PODD','MCHX','CHTR','TCP','BF-B','ALK',
'GER','SPRT','CALA','TNC','ADX','NDRO','TSU','PBR','FFA','ESRT','SINA','USAP','RAIL','DST','NXJ','LIVN',
'LILA','UCTT','EVHC','OAS','FCE-A','TRV','CFFN','RMT','LMCK','STX','NVRO','ORIT','NMA','ELLI','KAR','KTH',
'MEI','PNC','AWK','RLJ','GBNK','DISCA','PRGO','KLXI','BONT','JOBS','MTD','ADTN','ACAS','SSE','ATSG','APU',
'CYH','PCP','ZAVVV','EIGI','LKQ','KRC','ESND','MTCN','GLADO','HIG','BSBR','EDF','EOC','CRM','CSX','KHC',
'TPH','TLYS','SABR','FSM','TFM','APAM','SU','SIX','IMS','WPG','WPRT','LMNR','OXLCN','PNK','NILE','FOF',
'INT','DYN','YYN-TEST','STBA','SRC','FRA','CHSP','UBP-PG','SAVE','RVT','CRI','GFI','VG','TEP','LOCK',
'FCAM','PANW','FARO','WAC','CAG','WPC','VMO','WAFDW','INTL','CCRN','NUTR','NRP','AMX','UMH','THC','CRK',
'BPY','MTX','CBPX','CNL','MHNC','AMAT','TRMB','LOB','PCQ','SBH','QUOT','STT-PD','GZT','CNIT','AJRD','SIVB',
'NQ','BNY','JBN','CRY','FE','OAKS','CNMD','KTP','MED','MRCC','BUI','AFAM','EFSC','PACW','UVSP','SWKS',
'MMM','NTAP','PYT','VRTV','KNX','AEIS','WB','KEY','CMCM','SUNS','WK','ODC','LINE','NK','MGR','UPIP','JMM',
'CDR','PKX','RIGP','ASML','VOC','NPI','HEP','BBT-PE','BML-PG','USPH','DORM','DAN','BAM','ATLC','IBN',
'YHOO','CPLA','EMF','ELP','FDS','SFXE','WWD','LGCY','TRNX','CUTR','PVG','EWBC','ITRN','HPY','LPNT','CTRE',
'TNH','BCS','CEN','DFS','ORI','MCI','LOR','FCAU','PEP','EOI','AEK','RPXC','ARPI','BRO','AT','PRH','BKE',
'TRUE','EL','CIVI','SGRY','UBIC','MFLX','ERF','IMN','EOS','JNPR','PBH','CBRL','MQY','TRGT','RGNX','CPN',
'GDOT','GNE','SKM','PFO','PIR','PCF','SMCI','ESIO','CINR','CVBF','MFM','TRC','NXQ','BMO','FSCE','TRNO',
'SXCP','RNET','RST','REGI','FFIC','BRCD','ISIL','FBR','SGBK','DK','COP','CME','BF-A','GEL','LNDC','DISH',
'CVB','NTRA','REX','JPM-WT','PSEM','SXL','DGAS','MWV','VRA','SNOW','GBDC','UAN','CXO','UTF','DXM','DNOW',
'ESGR','HSEA','ZEP','TM','NCLH','CDNS','OMAB','MODN','PM','ZB-PA','VSCI','BIF','PFS','STT','PDM','DGX',
'SIR','ATI','OPHT','GPC','NADL','NWL','CMO','FVE','NE','VTRB','PRAA','DATA','AEB','TSLF','VMEM','AIN',
'EW','DPLO','OHAI','VDTH','AIXG','CKP','ICUI','AEPI','MPLX','RNR','AXP','DHR','ACC','CLMS','SZC','TI',
'TZF','EQGP','NMR','CAF','UCFC','DCT','WDC','CRZO','TRMR','LRCX','ATEC','BORN','BSL','GT','SNAK','SWI',
'EGLE','PRGX','SEED','MFC','SFG','CHMG','PATI','CRS','RRGB','HOV','GRFS','USB-PH','LIOX','TTC','ADS',
'MTB-WT','HWAY','SBAC','REXR','AJX','RACE','COF-PP','IVC','JPM-PB','RPM','PRO','MTRN','NEU','MTR','BTU',
'NTRSP','VNR','AGFSW','EMO','VKQ','EGO','TG','SRDX','NUV','APO','KAI','VLY','BHLB','BLOX','MIN','RMBS',
'KLAC','MPX','EVRI','PFK','QGEN','WRB-PB','AMBR','CCNE','MCX','KAMN','EGIF','IL','BWC','CHRW','AKP','NWS',
'NGS','SYUT','BBD','GLRE','WOOF','VNCE','FGP','VIV','ZINC','DSGX','MAV','MGLN','STT-PC','GJS','HMC','CRD-A',
'MGM','SFNC','FMBI','WNRL','TREX','CORR','FOSL','CTSH','FSLR','OAK','DXB','CSLT','LMT','LFUS','CCG','LBAI',
'CYOU','HDB','TRP','EBTC','CVO','PRTS','IDCC','KEYS','BFZ','HHY','RYAM','FGL','TRI','WING','ESRX','MCQ',
'PRLB','TSCO','NRF','ENLC','AEP','HAR','TEN','ACAD','ROK','JONE','WFC-PT','JAKK','CBU','LADR','TKC','NPT',
'EXK','NW-PC','FHY','CHN','SQM','TIME','WAFD','TEAM','MHK','TNP','RPAI','BAH','SGEN','SCI','ACAT','EDGE',
'FEI','MPW','ASMI','DCUB','EVG','ENH-PB','ALL-PA','CLS','CX','CTHR','MBLY','GHI','LKFN','STRS','BANR',
'SMG','ARMH','EDU','TD','UHAL','HCI','MUE','DLB','MIY','AVA','RGEN','FMO','AUQ','TCS','CTT','GBAB','ZB-PG',
'KMB','GJP','SRCLP','RSYS','AIY','RBA','NOAH','OXLCP','NCMI','TPUB','OZRK','TCB','HAIN','HON','GES','PEGI',
'OIIM','AMC','UFI','MCO','CAE','OAKS-PA','TBK','CPLP','PICO','CUZ','SBCF','FUR','DBD','FBNK','FWRD','AWH',
'MMS','CHH','WIA','EMG','IBP','BXMX','AVP','MDLY','MPAA','AWI','HGT','ASH','NKE','NWN','SNP','PJT','FORR',
'ONB','XOXO','TESO','PSEC','PJS','GOGO','MU','ISSI','QNST','SOR','SLW','TMH','PCN','PGEM','JTP','ITW',
'IHG','ABGB','PF','PKE','NICE','FNB-PE','FHN','PSMT','WDFC','SBGL','NCT','AMBCW','WPT','RBS','GBL','LPLA',
'KOP','BGCP','YELP','INVN','HQH','LBTYB','FRPH','PSG','CHOP','ANF','VLT','RF','ZB-PH','MWO','IX','BGT',
'MTN','FTI','WAGE','LTRPA','ARE','ARI-PA','ENVA','ADRO','IBOC','TTP','ATNI','NVO','KELYB','MSM','FMS',
'NJ','NRIM','SRF','ZBH','CBD','BSET','WGL','AES','WY','EROS','UCBI','TA','GPT','DD-PB','GG','GMAN','WGO',
'NUW','TUBE','CFFI','NP','CLF','CNBKA','WYN','CGNX','PHH','POZN','CRTO','TW','TS','SIGM','AYR','TRGP',
'KOPN','MIC','AOD','FXCM','HZNP','MFV','IMPV','TCRX','APTS','AVHI','GDP','CWT','SNC','BLDR','LM','DECK',
'LOCO','TYL','CRESY','ARW','MWR','SA','BBNK','CREE','CW','LITE','HIL','ICE','UEIC','UEPS','OSK','CYTK',
'CSU','EE','NVAX','PTY','BCH','PLUS','CZZ','SBR','AAL','AKR','DX-PB','INCY','LZB','LXRX','OME','BQH',
'TIER','LB','APOG','BMI','FRGI','RJF','TAHO','DWRE','NSS','LL','BTT','DDS','GOODN','ATE','HALO','FLC',
'MTG','MHF','ATRO','YY','AMAG','ISSC','NOW','OMED','STRA','NS','UTX','STLD','WMS','TMUS','AHH','WFC-PN',
'WD','DANG','ERI','EXTN','PX','PPX','HIFR','GLP','PFIS','FT','ROVI','MSI','SILC','BGS','MGA','RFI','PHG',
'TREE','ALLT','EEP','BSI','AVNW','WRLD','SOL','NSIT','UTMD','UNF','NNA','NFJ','HTGZ','SCNB','STC','NNBR',
'WRB','JRJC','FC','LNKD','BBW','VGR','CTAS','UL','USAK','KYN-PG','GTN','CCM','WFC-PJ','MGI','JMF','WES',
'SFN','JQC','MNRO','TSM','CCBG','GLT','MCY','GM','RBS-PR','Q','GLPG','CSFL','RSE','RGLD','ESI','BERY',
'GOOGL','BKK','AGM-A','GTY','FEYE','HSC','CHT','FFBCW','ANDE','AGIO','CJES','HBHCL','AWF','USNA','LDOS',
'OFIX','DAKT','LGF','STI-PE','LYG','QLIK','CVRR','PLCE','NGG','AV','FAST','PUK','SPWR','ASX','IRC','CVEO',
'SLRA','PSA','BRDR','MBT','FDEU','SAP','EPAX','NJR','AMWD','NXP','SRCE','FTK','WETF','AHL-PA','AMT','BUFF',
'YOKU','ULTA','JNJ','WSM','MSTR','DSPG','GS','MFG','OCIP','SEM','PCM','ABB','BDJ','WTI','MCRN','UTI',
'VNO-PJ','EQR','SUBK','HFWA','MLP','IBKR','WBAI','MDU','GK','SPN','ANGO','RBCAA','ANH','WSBC','FUND',
'XPO','SNV','GIS','ASEI','PCCC','CG','CST','LMNX','NX','SSNI','BCE','AUO','CNK','WLH','KEN','BV','SANM',
'IVR-PA','KEYW','KS','FOXA','PINC','SHAK','HWBK','RFTA','GOV','COLB','EDR','KSU-P','ZEUS','SCCO','ERA',
'FOGO','PWRD','FAM','AOSL','AMTD','BKCC','WWW','PLD','ROG','TMST','APF','BLW','BLD','WF','PPL','GOODP',
'EJ','KYN','NWPX','MMD','MSFT','MO','WBS-PE','EOD','RELL','EGF','UBA','JRVR','TEI','TMK-PB','CDK','ELNK',
'VGI','MTOR','MLR','GEOS','MPV','LPG','GAM','COLL','RAS-PA','CGA','CTU','EQCO','AXE','PYN','DLR-PF','EVH',
'RNST','ROCK','NAT','AUDC','TCPI','UPL','EPIQ','MHY','WEC','DSW','CEO','OMC','ROST','CZR','LBTYA','LOW',
'BAC-PL','STCK','PBFX','SPLS','FDO','TGS','AF','BID','YRD','ASNA','RFP','BYD','MFO','ALG','QRVO','LAWS',
'NTRS','KMI','LEE','KMPA','EC','CACC','DNKN','PBT','LOJN','FCF','BIE','BML-PL','BSM','BEL','INN','WPXP',
'AGCO','FPRX','EXXI','WSFSL','RCI','EXEL','HVT','CVE','CVG','HPS','PRXL','BML-PI','IPAS','DF','KELYA',
'GCAP','VRSK','DMB','JFC','AR','WFM','RJET','FIX','ESV','NQU','RICE','CHK-PD','FGB','NAO','TY','RQI',
'FDX','IBKC','BBY','SGL','DM','NSR','KNL','FCPT','CBI','XONE','SMSI','TCRD','MXF','SHBI','MBI','SBLK',
'ESD','SDLP','BNS','RALY','FN','QADB','QTWO','CBT','INTC','PSA-PX','T','FBIZ','NBR','UTIW','IGTE','DTF',
'SAN','KRA','BW','NBL','QLGC','JPEP','NWLI','FRO','CATO','DFT-PA','VNOM','AVD','QCOM','USLM','PFLT','SPXX',
'A','SAN-PA','VFC','RSTI','FPI','TFG','ISBC','FMER-PA','MRTN','MGEE','BTZ','GGP','VCV','IRWD','MOV','HCBK',
'SNV-PC','GGT','VRTU','GIB','TESS','NAN','CAS','SYT','ZB-PF','TRVN','PQ','GILT','NEV','QSII','HP','RY-PS',
'CGO','SCHL','UHT','STRZA','UVV','TAOM','MER-PM','ROLL','ALKS','CVTI','BML-PH','NIQ','ICD','HJV','CEB',
'IDT','LVNTB','PKI','WERN','ADNC','BKMU','KRNT','SCQ','BNK','SLB','EXPO','SON','WLKP','PRE','QADA','LINC',
'ECYT','CASH','TPZ','CLW','QURE','KHI','GSIT','CENX','BAX','CMRE','BCC','VAL','NVGS','CCSC','PAH','I',
'VSH','AAC','NEM','AMP','WPP','HIO','NIO','CKH','HYI','PSX','DGI','PBCT','DLR-PE','NCT-PC','MYRG','TMO',
'GFA','NTI','SALT','MIE','MNK','SSP','UA','MSEX','FICO','PTLA','TSNU','UNH','FXCB','NI','OFG-PB','FNGN',
'AVV','ATU','KNOP','GRUB','ABCB','DEI','USB-PA','PER','INWK','PCL','DW','DTK','CIR','NEE-PJ','RDN','ARG',
'PPP','FMI','EA','DATE','DUC','USAC','AMRI','TOT','CNCO','BITI','MTLS','HVB','EAE','MCBC','C-PN','FDUS',
'WMB','SMI','TRST','PGR','PDFS','ATAX','PNF','KKD','BT','OB','IOC','OUT','SODA','BKYF','TDI','RCPT','STNR',
'NDSN','COT','HBM','BHE','EGHT','VSLR','EXP','SFLY','EOG','KEX','DLPH','HKTV','LYTS','TGP','MGF','STAR-PF',
'JOE','R','ARI','PSTB','DMND','BSX','CYBX','TSC','WIX','FTNT','BRKS','CTCT','W','MYJ','MHO','BABY','CLA',
'RNWK','VRX','GDL','NVTA','HMLP','HSBC','FNV','SBGI','WAT','ATRI','FBC','NQM','CII','ENOC','JUNO','BKHU',
'ADSK','HII','NQS','ATEN','NSAM','ANH-PB','PXD','AN','AHL','CCXI','BCOM','TGA','TVC','GPM','MDCO','JPW',
'BUD','EXLS','EPR-PF','VCO','LHO','BCX','QSR','TDJ','ECC','IPHS','CSOD','ENV','RESI','NNN-PD','MAT','ECT',
'ETV','MSFG','OXM','APLE','VIAB','JGH','SKT','ABRN','NEWS','JEQ','ISD','CELG','NXC','UFPI','RUTH','PSA-PA',
'JHI','WSTC','BMTC','NXPI','HRS','TER','EDI','ALOG','WEYS','BCRH','IIM','NORD','SCE-PG','CXE','FCX','DNP',
'BAK','CACQ','BANX','LVLT','CYNO','CRAI','DX-PA','AWAY','TASR','VALE-P','DEO','OKSB','HTD','CVC','LLL',
'GTLS','HD','LBF','LGIH','AVT','XYL','KMI-PA','SPG','BJRI','GSL','TTWO','TRIP','HCN','VC','GSM','VGM',
'RY','NM-PH','CRRC','AA','MSCC','FI','BML-PJ','ALL-PB','RLH','CYD','SAFT','SAQ','SYK','CASY','CR','CCC',
'OIS','LDF','AXLL','GBX','GEO','CALM','VMW','BIT','LCUT','KE','CHK','ELON','WAB','SATS','NTK','FCNCA',
'KIRK','DPG','POOL','CCJ','AON','SHPG','MSK','CHY','AMCC','BOJA','PCI','CMG','SWZ','CAPL','SGM','GDF',
'NKX','CIG','PRGS','JNS','HBCP','CTX','RDS-A','GSIG','OXY','MAA','CNSL','MSCA','SF','SMFG','VIAV','AGN',
'ADP','WCG','BBT','GOOD','BWLD','WIRE','WYNN','HST','TCB-PB','PFG-PB','IIVI','PRSS','BBF','HNP','SSYS',
'RENN','TSI','WHR','JBHT','SBY','USG','MN','VRSN','MMU','CLC','ITG','NFBK','EPAM','RMD','OZM','EMR','MTEX',
'ARLP','AXTA','CUBE','WNS','MFRM','XNY','ISRG','NFLX','MOLG','UMH-PB','PAG','RSO-PA','TRCO','STV','GS-PJ',
'CPTA','MJN','LEN','PCH','GFY','HIE','CYS-PB','FSC','CCU','GGG','AYA','HTA','PLNT','NKTR','IPHI','GNT',
'HK','"','FL','CGI','MCR','PDI','ING','WFC-PQ','MMYT','CTRP','NTGR','NKA','CISG','RE','CBOE','DCUA','ABX',
'PJC','HTR','WMAR','MS-PA','PFSI','CECO','FPT','CTCM','SWNC','ITCI','DSKY','SUSQ','MIK','NUS','RAVN',
'ATML','NPO','BXS','CUB','CNO','BFR','QSR-WI','ATRA','DOOR','OXLC','CPPL','DSL','TEF','"','ROSE','CDE',
'FNLC','ORLY','BGC','OMCL','WFC','EMITF','ASFI','NM-PG','TR','MTT','DCIX','JMT','JHS','MUA','GERN','EIX',
'AFB','GLOG','TCPC','MSL','BEAV','VIA','TTEC','CCE','MYN','PRTA','GMCR','CTRL','ELA','BHK','RUSHB','PGNX',
'GXP','SBNYW','PDLI','SRI','SUTR','FCN','GRX-PA','FNFG','URBN','KPTI','DOX','CEE','PHMD','IGLD','OVTI',
'C','AMBC','CLGX','HAE','BGB','SBBP','BKS','JMEI','TPL','NEWP','CAB','IDE','HNI','CHW','EGOV','HYH','PE',
'NYLD-A','CVS','CUBI-PC','BCOR','CAMP','BSD','DX','KN','PDS','ELS','TWN','MFT','BNJ','SGU','MDSO','STFC',
'NYMTP','KST','HTBI','SCVL','TIVO','FAV','GS-PD','BAC-PD','SWJ','HHS','ACRE','NVR','ARUN','RES','OFG',
'EGL','MKC','NPK','VIAVV','SLG','VRTB','SNI','KR','COKE','CBF','WGP','OMN','HTZ','MHLDO','IND','IRL',
'ESLT','BCEI','BXC','IAG','SONC','KANG','TPVG','SUN','INO','TDG','CSTE','ISG','CPAC','TLLP','YPF','MMT',
'HPT-PD','SONS','BIN','KEF','BBRY','FBHS','SMM','NSA','GNW','PCYC','GRR','PTC','INTLL','GSI','GOF','DEX',
'CMS-PB','MVC','AFT','ACV','BOOT','BCRX','SM','PTEN','KZ','KITE','AL','ORIG','CDW','BRCM','SSB','HSTM',
'EQS','SPPI','IGT','MR','USB-PO','NUO','TGT','DISCB','TRS','GEQ','HBANP','CTS','JOUT','OREX','SJI','GEB',
'ST','CBG','EURN','AMH','KBH','SWFT','BBCN','WRK','IBM','CSBK','TWI','SHLX','IIJI','ED','BAC-PY','ALR',
'TLGT','ADPT','ZNGA','KYO','SREV','IRBT','F','ARMK','BCA','CBPO','MOG-A','SXT','TBI','CIE','CTRN','AGRO',
'IPI','CMCO','TANP','PBI','AIT','OFS','SMP','RBS-PI','LYV','MIFI','EBIX','BXLT','DG','WLL','RGA','NXN',
'AF-PC','NBB','LAZ','EMC','MHD','GILD','KTOS','CABO','BIOS','AKRX','PAM','TCO','NVCR','STI-WTB','VAR',
'DSXN','SHOR','RNR-PE','CXRX','PULB','EDD','BLUE','GB','ARCB','STAR','GPRE','DY','BITA','REXI','EVT',
'MPC','SPOK','BPOP','DTQ','MON','SJR','LXFR','HR','GNL','EZPW','XBIT','TCBIL','REMY','"','STON','BC',
'NAV','CMC','TOWR','JTA','GHY','DRI','SMLP','GHL','SYA','TUMI','OEC','MGIC','EHI','INFY','TRAK','EXPD',
'STAG','GNCMA','AC','NAC','MC','FRC-PA','SEMG','BRKL','MX','SKX','PTXP','AMRK','MBFI','CAR','VLGEA','JCI',
'VEEV','FLO','PNRA','BGFV','IHS','GAB-PH','NAV-PD','TSQ','RTEC','ACN','CRR','CSTM','FLT','YNDX','PRSC',
'ARIA','CSL','SLCA','TXTR','MFA','MA','JCAP','NWY','KIO','MOSY','OCN','BPFH','CNXC','AEGN','GDV-PD','SGMS',
'HOG','ACG','FFBC','SGI','HPT','HUBS','PPT','WIFI','PEB-PA','PBY','COL','FNF','IR','TEVA','CTB','DTE',
'ENH-PC','DHX','SEMI','CPT','WNR','ARU','RH','BX','TNP-PB','AMNB','DPS','D','IM','PVTB','WSFS','COR',
'GEF','GDO','ACXM','DDR','MCS','POWR','MTW','RGR','TK','TTF','GEK','DYN-WT','UBP','CMCSA','WTFCM','KOS',
'BP','DFT','EEFT','HWKN','MWW','DVA','MG','MLM','K','RNG','DCI','LECO','MTSC','DEPO','BOI','BRT','THRM',
'QEPM','COG','ANGI','PAY','VIP','REXX','GHDX','SCG','WR','CIF','FSFR','HYB','RUSHA','Y','CVA','GWRE',
'MPG','ARO','"','NEWR','HBNC','SNHN','HGR','CPS','NSM','UTEK','SALE','BMR','SVVC','CO','ERJ','HSFC-PB',
'BRK-A','SID','FLS','TUP','AHP','IHC','EXAM','FORTY','FORM','PAYX','RKUS','MUI','NOV','EAB','RPT','DRNA',
'HCSG','DHG','KODK','KLIC','DRD','ANTX','AGIIL','UDR','WIW','PJH','SQ','BURL','TWOU','PCAR','TDF','LTXB',
'FBNC','VVUS','WSBF','NCA','RPT-PD','TSYS','GAME','JMG','NVDA','HCOM','CAC','HBAN','SLM','MKC-V','EEA',
'HBOS','TYC','SHO','BEAT','BETR','UNP','BWG','CIB','DNI','ABAX','AI','RAI','PCTI','TXRH','BFO','ACTG',
'CONN','KSS','NGLS-PA','MDR','JDD','AIF','INDB','WHG','ZBK','NCV','ALL-PC','LEO','BH','MTDR','FMN','CEVA',
'IRDM','JW-B','MEP','COHU','ESSA','PGP','DEST','BHL','OKE','SSD','VSTO','MGPI','TCBI','HSON','SEAS','OHI',
'HPQ','NPM','HLF','FRM','JPM-PG','HE','ACSF','BIO','BAP','AVAL','XOM','TEGP','VPV','AGNC','DIAX','EPC',
'COHR','RSPP','SIRO','LIFE','LPX','SAIA','NHI','MFD','DISCK','OPY','AKO-A','LDL','GUT','ECOM','IPG','BMRN',
'BWXT','CHCT','JWN','VTR','CTMX','OMF','SDT','IOSP','IGD','WHF','NID','PZN','VVR','CPF','GAIN','FIZZ',
'AINV','EVGN','MASI','TCI','IRS','JGV','SD','GTT','JBL','AMCN','MXWL','RDWR','PTIE','ONTX','OUTR','RAX',
'HOLI','RHP','TECH','HBHC','WPZ','CE','FELE','INFN','SSW','ZMH','CNNX','STJ','TCCB','CAL','TCBIP','NDP',
'SIMO','CSRE','TLI','OSBC','HCJ','MHNA','JMPC','VLO','TE','RYI','RTIX','PVH','OGE','RUK','PETS','PSF',
'UCP','KEP','VZA','YUM','FCT','MPEL','CTW','RELY','SOHU','PFGC','PKOH','BCOV','IMMR','WRES','CPB','ULTR',
'THR','SENEA','ICL','RGT','DKT','ADUS','HTH','IFF','LUX','AFSI','PFG','ORBC','HTCH','ANFI','TKR','FUN',
'INF','VSI','ALSN','SYNA','CHKR','BOTA','CKSW','SLAB','EFT','UBSI','SBW','XRAY','PKO','CVCO','FSD','SHLO',
'STRZB','DYN-PA','BBOX','FTAI','CCIH','ENL','IPGP','AKO-B','LFL','ANET','KEG','HPI','FMC','WSR','PAGP',
'CSI','AOS','BBX','FIG','SEIC','PERY','AMRS','UBS','GNC','B','HDP','FGEN','SPXC','DLR','LLY','RJD','ZUMZ',
'GRO','ISIS','AP','SNN','UMC','FTEK','XIN','MMLP','WM','CATY','AGM','PEO','WWWW','COF-PC','DCO','TDS',
'NVS','NRCIB','USDP','CB','MS','VOYA','DGII','ALNY','TGI','CAJ','RDEN','STB','SSTK','NCT-PD','UACL','GLF',
'SRLP','TTS','NWSA','SP','AG','WEN','SN','FCE-B','POST','SPB','EBS','VNO-PI','SLRC','DRA','PEN','XLNX',
'AMRB','PSTG','PRI','LAMR','LF','AZPN','CSAL','TRR','ADI','ATW','AGII','WBA','SWM','MCRB','HEI','CHI',
'CSII','JPM-PH','NANO','TXN','LNN','IRG','PG','UNTD','CCI','EQM','ACTS','AFG','HTS','TAXI','ALLY','ETG',
'RHI','GPRK','NC','LITB','SCHW','AIRM','GRX','TUES','ATO','RCKY','IPAR','GIII','OGS','CATYW','NLY-PD',
'ARR','CFR','CRVL','SAM','MIL','AB','ADVS','IGA','SQBK','CLVS','CDR-PB','SMTC','CVT','AXON','BLL','ROYT',
'DIOD','SNPS','GMZ','ZFGN','QLTI','ISLE','GPS','WLT','CCLP','HRTG','OSUR','MCRL','AZO','NAME','AGFS',
'CLD','CHMA','CIA','AJG','HLS','EBAY','RRM','DUK','ARRS','TRIV','DHXM','WNC','FR','TFSL','GBCI','LNCO',
'JOF','LDRH','RYN','WMK','APB','APA','ETY','LPL','MLNK','SAFM','CBNJ','SXI','NPTN','CORE','RRMS','NEP',
'BRLI','CROX','PBF','CTRX','BAC-PZ','TOWN','QIWI','NTT','CFC-PB','LUK','JFR','DRQ','TSN','BAC','CFI',
'SZMK','BNCL','ABT','THO','CSGS','ZBRA','FLDM','QTM','GPN','WBS-WT','HAWK','BW-WI','ACOR','UVE','DE',
'GJV','TFX','FMSA','PPR','LXFT','AZUR','DOC','SUNE','MDC','CTL','ICB','JPM','AES-PC','SHEN','NFX','FMER',
'PKD','LRN','HOS','DLTH','TILE','ININ','DOW','HLIT','VEC','ABEV','VOXX','EARN','AIB','GOLD','AVGO','FMD',
'BPFHW','GIFI','GNRT','BKT','GLAD','MS-PI','EXC','MTZ','MPA','APH','EVA','APLP','CHFC','DTLK','TWO','SNE',
'CODI','EDN','SYF','VMC','WHX','CONE','CKEC','ZTR','KCC','VOD','SCD','PES','PZC','DAC','TRQ','RGC','ECCA',
'HMST','WAL','MPWR','RENX','KGC','EVC','EV','ENTA','NLS','HGG','UZA','CPK','OMI','EMES','CACI','FIS',
'EQT','ON','ZTS-WI','DLR-PH','EMN','BRX','NUAN','PMT','SNCR','MANT','VMI','HDNG','MY','AGR','INOV','HSEB',
'NFG','STM','ELRC','FFIV','BFAM','REG','BMY','OPWR','TMK','PWOD','BDBD','HIW','LEA','HT','BLMN','PRU',
'VCRA','CVLT','ALTR','OMAM','AAAP','NOK','HTLF','RKT','HWCC','DTSI','USB','PTNR','ADT','SIAL','FAF','EBSB',
'MTSI','GAB','SB-PC','MHLD','NUE','MHI','KMX','HBI','THG','BDN-PE','CPE','RUN','IDXX','MRC','PCTY','PH',
'FSBK','EPAY','ZOES','AXS-PC','EIG','NAD','XNPT','JTD','SPIL','AIR','DMLP','ROL','MET','FCFS','UNM','TKF',
'SHOO','STE','BTE','NATI','CCMP','ASCMA','TWX','NBHC','CBS','OLP','NLSN','BEN','WCN','MCN','AVG','BEBE',
'PB','HUSI-PF','ENH','JPM-PA','ITUB','AHT-PD','CENTA','MIME','FRSH','NNI','WILN','LOGM','MDAS','AVAV',
'LSTR','KBR','EVF','FPO-PA','TEX','TEDU','S','STMP','NEWM','PNNT','KMDA','VYGR','MET-PA','TOO-PB','TYPE',
'AFA','IBCP','MEN','XTLY','IO','GSBC','WFC-PL','BLK','TAST','LQ','O','BOX','GI','CCOI','BOFI','ITIC',
'KFX','PNX','MT','CEL','ALCO','PENN','BOCA','HYF','MAR','TROW','PGZ','MANH','CATM','MIG','PEI','MOS',
'HYT','BPMC','ALDW','GCV','MFL','EXG','NWBI','OSBCP','JKHY','AMFW','GARS','JPI','VNRCP','AIG','CWST',
'MEG','TTPH','RRC','RCII','AAT','SLGN','ETN','PDT','JEC','PAAS','KF','ACCO','APOL','GRA','MTB','APD',
'SPWH','PHD','SYKE','RCL','ETP','SFM','RWT','PAR','VWR','HMY','SEDG','ENZY','EVER-PA','WPX','KMG','NRF-PD',
'NTZ','MAS','MNE','CBR','CTR','NRF-PA','HIBB','Z','DAVE','AMSWA','SBLKL','ACE','ACTA','CCZ','OIA','SNHY',
'DRE','FDI','ARR-PB','SPKE','HNR','ENLK','TZOO','PKY','ZU','NBIX','KFY','HRB','BONA','UDF','FSB','MCA',
'ITC','MQT','AMG','ABBV','ENR','CAVM','ABCW','AMTG','MCC','JPC','ANW','OCLR','AET','LOPE','AVY','SUP',
'ETO','HEES','VRNS','CCL','REIS','AFW','ISCA','SFBS','ZIONZ','IT','STAY','FARM','BKD','AMOV','DGICA',
'COO','RBS-PG','EVN','IONS','FFKT','AMSGP','ICPT','GLPW','RL','MDM','V','BBL','PPBI','CCS','CPHD','GYC',
'GGZ','NRT','SGZA','ACIW','RELX','RVSB','SEE','AAP','NAVI','GDL-PB','P','NGL','GNK','CAT','PDCE','EVEP',
'WCIC','ASR','SNY','BLH','BZUN','ESL','MCEP','CHUY','TDY','KRFT','LAYN','LEG','STKL','OFC','BBRG','EVR',
'IPXL','UTHR','EXLP','MGRC','AHC','MWA','PFE','BHBK','LMNS','YZC','URI','WIN','AGM-PB','VICR','GEVA',
'HELI','SRT','BRSS','ACHC','AM','FBRC','GNRC','SE','USM','ADAP','BAC-PE','DAR','ENBL','GE','AMGN','DMO',
'NDAQ','CPG','NMRX','OFC-PL','FIVE','MKTX','ARTNA','VR','THGA','HLI','DUKH','GLBL','WEX','NIM','CC','DDD',
'HEI-A','HIVE','ACET','EQY','CMS','EFM','GME','OTTR','CAFD','CMTL','SWN','ASTE','CSIQ','SPH','RHT','EXPE',
'AFSI-PA','AVK','DRC','FLTX','MLHR','SEAC','CENT','GRPN','AXR','MKL','IXYS','LDP','NTX','FLOW','HTGX',
'RLGY','ARCO','WCC','MSG','HGH','OI','PZZA','ADBE','JRN','QEP','ABMD','PNC-PP','MCHP','PSO','DO','VASC',
'SLMBP','FRME','TOPS','WMC','CHE','AEO','NPD','VNRAP','ALJ','GDDY','SLH','TNGO','HAFC','TRMK','JBR','PDCO',
'CAM','BCR','BWP','FRC-PE','AHL-PC','KNDI','AXTI','COTY','BRKR','NTL','HIX','TMUSP','MSF','CNTF','EBF',
'BELFB','FXENP','ATHN','PBPB','TV','YDLE','AIMT','PHX','SKUL','EVTC','VVI','KRO','HUBG','ASA','NRF-PC',
'ENS','ENTG','FITB','BIIB','AGU','PGC','POT','EFR','SHW','NAVG','ACLS','BZH','TAX','CTXS','OSIS','ASPN',
'NTCT','JHA','ZG','NEFF','WIT','UFCS','CECE','DBL','MATX','TPX','CNS','IART','XOOM','ARDC','CHEF','NNC',
'MXE','ASND','HHC','EVER','TWTR','ARCC','CTLT','BPI','BOBE','JMPB','STRL','OOMA','HEQ','ODFL','SWIR',
'CIT','HMHC','VIPS','DIN','MZF','ARNA','NTP','PFMT','VIRT','BIG','LCI','LQDT','MSGN','IRM','LMCB','RM',
'SGYP','BSRR','VEDL','BVN','UNT','CEA','UN','AEG','CTG','GAS','SCOR','BLT','CLDT','SGF','CWEI','IGI',
'CFX','EPD','HY','TBBK','CHA','HXL','CEMP','BCPC','PEG','MRGE','NXTM','WEA','AUY','GFF','VBF','MXL','MINI',
'IMGN','VRTS','YGE','ASYS','ADM','HUSI-PG','SPNC','TEG','SXE','BPFHP','TICC','UE','GRAM','HSIC','NKG',
'ENJ','TVPT','HZN','GGE','PBA','SPE','JMI','CDI','SFL','ZAGG','SNA','BMA','SYMC','AVB','BRC','ALSK','PMCS',
'PRIM','CI','FSS','MRH-PA','BOOM','SBSI','BKFS','FDML','AMRC','AFSD','QUMU','FCS','METR','NIHD','BCS-PD',
'VRNT','NTLS','SPA','WTR','TWC','ECOL','RIG','HDS','ALV','BFIN','SXC','BABA','PROV','CHL','MVT','CNV',
'MTCH','MTL','MLAB','MDP','EMMSP','SLF','KB','TRUP','SPLP','AHT','TERP','BOXC','BBDO','HOFT','COWN','BCO',
'CCK','DNB','USTR','AIZ','TCBIW','PLXS','EPR','KING','PAA','H','MRVL','NRF-PB','NATL','CTQ','GGM','DEG',
'KORS','BAC-PW','TECD','ABC','ENZ','ESNT','PBR-A','VER','TMHC','JAZZ','COMM','BAC-WTA','TROX','CGG','RT',
'NATH','MAN','MHG','CELP','FSRV','RAS','CNX','BKH','JST','NNN-PE','NWHM','KODK-WT','PRFT','OKS','JHP',
'CALX','MSA','NLY','TREC','MCD','FCH','CINF','IVH','M','BELFA','BNED','BZT','PHII','ENVI','NM','FMY',
'CHCO','FIBK','FTR','QQQX','BRFS','WG','NCS','MYI','CBB','KFS','ATV','OPK','BWA','AKS','WASH','PLAY',
'ETR','ENDP','MAC','MNR','RFT','CTWS','HLT','SASR','PMFG','TPC','CABO-WI','MBTF','GF','RP','SHOP','AHT-PA',
'GDP-PC','PYS','UMH-PA','BLX','BAF','EXAR','GBLI','SDR','SUM','WAIR','UGI','CLMT','AIV','LORL','SRV',
'BKU','UTL','JPZ','SGY','ALE','MNTA','EROC','AROW','BOKF','HTBK','OLN','NMT','TDW','LBTYK','TYG','AMSC',
'FRAN','COH','XLS','THRX','LXP','PRA','SAIC','NDLS','ABY','G','SEP','WU','HURC','AGYS','IRET','VTA','ABM',
'NYT','HPP','FITBI','JBT','DCUC','TTEK','SVU','OTEX','FOR','MTL-P','ECPG','RARE','PLKI','FUNC','CRUS',
'VJET','THOR','BJZ','HTGC','HL','REN','TVE','CL','UPS','FII','E','AEM','AGNCP','ZPIN','TCK','FTD','ZION',
'NEOG','QLYS','CMP','FCB','MCOX','CMCSK','EVLV','MDLZ','EGP','REGN','MSD','KFI','GWR','DDF','EVDY','BBG',
'CVGW','FLWS','PNW','DHF','SWHC','DL','LLNW','NES','PNM','ORBK','VECO','FNB','RLOC','INXN','TAP','FANG',
'CMI','MTH','GJO','PLPC','DWSN','AGX','MUR','GTS','AXL','DMRC','HZO','POR','POL','AGO','PEBO','DRH','PACD',
'EDE','SSNC','MSP','GDV','MTRX','LNT','DAL','ARAY','LUB','CBK','WMLP','LCM','MDRX','IHD','PCG','RDY',
'COR-PA','MBVT','PGRE','MH-PA','TITN','ALU','GNBC','DVN','HTY','RBCN','AAV','SJT','HQCL','AAPL','RXN',
'MANU','MTGEP','FFG','PHK','JJSF','BSFT','GJR','JMLP','GLPI','BREW','CP','GVA','ANIK','KKR','AWP','LMIA',
'LBRDK','ARCX','KYN-PF','COBZ','ETB','RENT','RDS-B','NNN','BDX','RAD','PML','FINL','THQ','ENSG','FSYS',
'ACGL','HSNI','ORN','EXAC','RF-PB','BXP','CFNL','WMGI','ZFC','ACM','NAP','MEOH','CBZ','AROC','WY-PA',
'GOGL','ETFC','GSK','BRK-B','SPTN','WLK','TRN','STOR','CF','RECN','CLH','RIT','DIS','ETM','WTFCW','HRC',
'JGW','BAS','TPRE','TDA','CPGX','SBNY','KT','MDVN','DHIL','ATLS','MRCY','NBRV','INFA','MUX','AA-PB','VICL',
'MRO','SCTY','CAKE','AIMC','ICON','FPO','ISP','CNI','CMFN','LXU','MOG-B','WTS','EZT','NVMI','INAP','GUT-PA',
'MRLN','BDN','OLED','SKYW','VRTX','CTV','BSMX','AFSS','SENEB','BHP','EEQ','NCOM','ICLR','ANR','JPM-PC',
'RTN','NMY','GHC','AZN','NYLD','NRZ','TSEM','SB','ALL','KRG','TSRO','CVX','CS','AKAM','BBVA','KED','NBD',
'CNHI','NNY','WBK','IPL-PD','IPCC','LNC','KALU','UNVR','NRG','JCP','SVA','KSU','HRL','KMM','TI-A','CMA',
'CEM','SWX','AMSG','DFT-PB','BDC','MPSX','ITT','BANFP','SHLDW','JBK','EXFO','XON','PVA','SJW','IILG',
'ZNH','FLR','LSCC','TCBK','KVHI','MYC','CCO','RNF','QIHU','LANC','OIBR','ZIONW','UBFO','HCCI','ZIXI',
'GSOL','BIDU','MDT','ABG','RUBI','JPM-PF','LPI','DV','TLK','XCRA','ETSY','KMF','CM','DLX','SGNT','SPNE',
'PKG','LOGI','NPP','GPK','VSEC','THS','XEC','FLIR','HMIN','DEA','DBVT','GIM','BHI','PYPL','EAT','UFS',
'SJM','LUV','CSCO','MMP','HRG','SFUN','KATE','XUE','ABDC','KYTH','FDC','CTBI','ZX','KTF','INFI','PLOW',
'SIG','LDR','GCI','JAX','KYE','UIS','ETH','XRS','HQL','FOE','HOMB','LGI','MNP','XHR','DSM','IBA','AYI',
'JOY','TANN','KIM','ARII','BDE','SCS','SUI','KCAP','ELB','DLTR','AVNU','EVBS','NL','NICK','ATVI','WFD',
'HTLD','NR','CRC','LNCE','BECN','INGR','OC','LII','NEE-PI','FISV','SCL','CAA','JE','AME','EHIC','NRK',
'EBR','YDKN','NIE','DCOM','PATK','DD','NPF','VZ','MUJ','CERN','ORA','VIVO','CRT','NOA','CNQ','NYMTO',
'SCM','LG','ERII','PBYI','WHFBL','NQI','LGCYO','GWW','PSB','CHMT','AGD','MTU','ELU','PSA-PR','NCTY','FOXF',
'CUBI','HUM','HFC','EMZ','EPE','CHDN','ATTO','GLNG','EXTR','SNX','CWCO','FNFV','BEP','MCRI','EGN','INB',
'CLNY','DSE','HASI','GBT','EMD','SPSC','HCN-PI','ALEX','HT-PC','CRH','BRS','SYX','PMO','LPT','PHI','SBRAP',
'BK','CLR','CNP','MERC','ZAYO','BBN','KEY-PG','HELE','PN','GDV-PA','DKL','DFRG','TU','KAP','SIFY','RRTS',
'TSRA','YUME','WDAY','DQ','UBNT','BFS','PSXP','PCRX','NHF','WOR','TPVZ','LND','XNET','KFH','TWIN','FLXS',
'ASPS','OII','ACW','YRCW','PMC','ERIC','IEX','BALT','KOF','ECHO','ETW','NBTB','BOH','MIND','WST','BST',
'ELGX','ARCP','EQC','CSV','JNP','MKTO','MOBL','EPZM','NYCB','TARO','SMRT','HPE','SPR','WDR','IQI','FENG',
'EME','IVR','BGG','CLNE','BPL','NAZ','SFS','GCO','CAH','CDXS','CTY','GSJ','CCD','MYGN','MGU','QUAD','VA',
'RZA','SIGI','TAL','CEQP','PHIIK','GSL-PB','FPL','GXP-PE','PTCT','FFNW','GSH','JLL','CSGP','TOO','INGN',
'LABL','JPS','MLI','MNI','CMPR','MIXT','INCR','CXH','PMM','FSCFL','ES','POWI','STLY','MUS','JKS','LC',
'CLB','CSQ','ZCVVV','ARES','ACP','OCFC','SYY','ONTY','MORE','AMCX','LONG','DDE','CRNT','WFT','NSSC','FUEL',
'ALX','ESS','WPG-PI','CIEN','HMPR','CIO','MOMO','VPG','DOV','NMFC','DWA','GJH','BR','UGP','GD','CMU',
'NRCIA','MELI','GAM-PB','WWE','AEUA','FPF','PIM','GLOP','BTA','ORAN','SYNT','MXPT','DMD','ETE','LMCA',
'CPIX','RMP','SQNS','SRSC','PAC','PFBC','IGR','RDC','SNH','CHS','EFC','CBL','CBSH','CLV','WSO','PCO',
'AHS','FEIC','NGLS','PERI','MTGE','CSWC','ALGN','GLUU','COVS','GEN','FEO','BGX','KWN','CHMI','DGICB',
'XRM','MRKT','IMAX','NEE-PP','SSI','KND','YORW','ILMN','BBEP','HCLP','WMT','ALGT','VLRS','UBSH','GLW',
'PWE','FIF','SNDK','CLDX','CXP','MUC','PFD','TTMI','JHX','KO','ZEN','ODP','MATW','HUSI-PH','SPAR','ARP',
'EXR','MRIN','NTRI','AMKR','HF','NEE','TLN','CSS','WHZ','SIRI','ANAT','IDTI','AAON','XRX','SO','CBO',
'FELP','SOV-PC','JIVE','CVGI','LTRPB','LTC','DFP','TDC','GHM','WWAV','STNG','NUM','PNR','PEI-PB','TCAP',
'AEH','MYF','XEL','NMO','NSC','TECU','DNR','PAYC','GIL','XXIA','NGVC','NXR','MNST','SPLK','ULTI','CYS',
'DLNG','NMBL','GPOR','L','IRR','FFC','WIBC','EHTH','VSAT','TLP','JP','VSAR','CSH','GRMN','HSBC-PA','MITT',
'TJX','SCAI','IID','HLX','GPRO','ONDK','PAI','SRG','THFF','HA','GOL','ASGN','FRC','MRK','ASB','RGS','LYB',
'NRE','TGNA','RYAAY','GMLP','TTM','CMLS','BANF','CPA','NMM','CTZ','NYMT','PSA-PY','UMBF','TNP-PD','KBAL',
'ADC','DSU','RAS-PC','CY','WTM','FSAM','WRE','OPB','RNP','IP','AVEO','MOFG','HMN','KTN','MIDD','CETV',
'BKN','SC','FCBC','LPSN','GRP-U','VNRBP','IVZ','CSUN','HW','MMSI','TXT','BMS','CUDA','MENT','KRNY','FULT',
'UTSI','HOT','GASS','ANSS','SHLM','FB','HUN','NBBC','MDCA','VNO','PPG','PNFP','MBWM','TC','HTS-PA','MCGC',
'BUSE','CRWN','DVD','RELV','FRT','ACH','ONE','TSO','BGR','NXRT','MAIN','KCG','FLY','SWC','AU','RLI','VET',
'ALB','RSG','ARC','JLS','ISF','IFN','APEI','JMP','WTBA','TRK','AOI','HCP','SZYM','EXCU','AXS','POWL',
'STO','EOT','SNBC','NTES','UNFI','BTO','IACI','CXW','IIF','LEJU','PFN','FOX','ELY','NYRT','EQIX','AMID',
'WEB','FIT','CLX','MRD','NSL','KTWO','SFE','PCLN','GPI','CA','BBBY','MD','VLP','SCX','STI','BANC-PD',
'LULU','TEO','ARCPP','KSM','ALRM','MLNX','PTR','BSAC','CIM','WPPGY','VALE','WUBA','BA','SHI','OXLCO',
'ZF','PWR','GIMO','PNY','LBRDA','UBNK','EAA','HTHT','HCKT','FWP','FISI','SQI','TIF','ACHN','WABC','SHG',
'IEP','FDP','CYBR','SCSS','PMF','ALLE','HRZN','NCR','TSE','UZB','FUL','GWB','AGI','FF','HIMX','SNR','AHGP',
'TNET','LVS','WBS','MUH','MSB','MMI','BDGE','TSL','HSY','PEB','WSTL','MEMP','PII','PGH','SCE-PH','MORN',
'HQY','CRAY','IDA','MVO','SIEN','HI','OIBR-C','SLTB','HTWR','JCOM','VTTI','BGY','AFL','TDOC','AWR','FSV',
'BBK','WRI','PIY','PLCM','TEL','AFFX','MSCI','AEGR','AMED','CLI','BPT','SBRA','EZCH','BIOA','NMK-PB',
'CPRT','NMI','SAH','KEM','MKSI','HSII','NQP','CNC','MYD','PFL','AER','CHGG','JBSS','WFC-PR','TSLX','AAWW',
'APIC','BXP-PB','VIEW','ERIE','NEE-PC','VTN','ALXN','ROIC','AEE','CHKE'
]

#nyse_nasdaq = [ 'HAL','CASS','GGB' ]

parser = argparse.ArgumentParser()
parser.add_argument('--start', help='start date yyyy-mm-dd')
parser.add_argument('--end', help='end date yyyy-mm-dd')
args = parser.parse_args()
print args.start, args.end, len(nyse_nasdaq)

open_prices = []
close_prices = []
high_prices = []
low_prices = []
volumes = []
symbols = []
length = None
for s in nyse_nasdaq:
    cmd = "/usr/bin/curl --no-buffer --retry 3 --silent 'http://real-chart.finance.yahoo.com/table.csv?s=" + s + "'"
    try:
        out = subprocess.check_output(cmd, shell=True)
    except:
        next
    active = False
    op = [] # open price
    cp = [] # close price
    hp = [] # high price
    lp = [] # low price
    v = [] # volume
    dates = []
    for d in [l.split(',') for l in out.splitlines()]:
        if d[0]==args.start or d[0]==args.end:
            active = not active
        if active:
            dates.append(d[0])
            op.append(float(d[1]))
            hp.append(float(d[2]))
            lp.append(float(d[3]))
            cp.append(float(d[4]))
            v.append(float(d[5]))
    if length is None or length==len(dates):
        length = len(dates)
        open_prices.append(op)
        high_prices.append(hp)
        low_prices.append(lp)
        close_prices.append(cp)
        volumes.append(v)
        symbols.append(s)
        print 'symbol', s, 'length', length

print 'len(symbols)', len(symbols)

# write numpy arrays as hdf5
h5 = h5py.File("nyse_nasdaq.hdf5", "w")
h5.create_dataset("open", data=np.array(open_prices), dtype='f')
h5.create_dataset("close", data=np.array(close_prices), dtype='f')
h5.create_dataset("high", data=np.array(high_prices), dtype='f')
h5.create_dataset("low", data=np.array(low_prices), dtype='f')
h5.create_dataset("volume", data=np.array(volumes), dtype='f')
h5.create_dataset("symbols", data=np.array(symbols), dtype='S10')
h5.create_dataset("dates", data=np.array(dates), dtype='S20')
h5.close()
